name: gql_websocket_link
version: 0.1.4
description: GQL Websocket Link
repository: https://github.com/gql-dart/gql
environment:
  sdk: ">=2.7.2 <3.0.0"
dependencies:
  meta: ^1.1.8
  gql_exec: ^0.3.0
  gql_link: ^0.4.0
  uuid: ^3.0.4
  rxdart: ^0.27.1
  gql: ^0.13.0
  web_socket_channel: ^2.0.0
dev_dependencies:
  test: ^1.14.3
  mockito: ^4.1.1
  gql_pedantic: ^1.0.2
